nacos-group/nacos-sdk-python

nacos/client.py, test/client_test.py
1. add test case for list naming instance with offline hosts
2. add test case for add/modify name instance for dict metadata format
3. modify get_naming_instance to support cluster parameter changes
4. bug fix on Windows system that deleted a unique listener item
=> add test case & bug fix on Windows system that deleted a unique listener item

.gitignore, setup.py
Optimized setup to auto packing and uploading, it just runs `python setup.py upload`.
=> Optimizate setup to auto packing and uploading

.gitignore, README.md, nacos/client.py, setup.py, test/client_test.py
1. Optimizate `setup.py` to auto packing and upload
2. add parameter 'ephemeral' to add/modify/remove/beat funcs, default value is True
3. add test case for sending instance beat with dict metadata format
4. modify README.md to add 'ehemeral' description
=> optimize setup.py & add ephemeral

nacos/client.py, test/client_test.py
bug fix: remove install_opener (this is global setting will affect other requests in the same process), so here make proxy settting focus on current request
=> bug fix: remove install_opener,  it will affect requests that do not require a proxy

v2/nacos/naming/backups/failover_reactor.py
to solve issue #55 
add nacos.naming.backups for module naming
=> [ISSUE #55]Feature support grpc: add nacos.naming.backups for module naming

v2/nacos/common/preserved_metadata_keys.py, v2/nacos/common/utils.py
to solve issue #73 
add module common
=> [ISSUE #73]Feature support grpc: add module common

v2/nacos/property_key_constants.py
to solve #76 
add property_key_constants.py for the new vesion of python sdk
=> [ISSUE #76]Feature support grpc: add property_key_constants.py for the new vesion of python sdk

v2/nacos/utils/app_name_utils.py, v2/nacos/utils/net_utils.py, v2/nacos/utils/sign_util.py, v2/nacos/utils/validator_utils.py
to solve issue #74 
add module utils
=> [ISSUE #74]Feature support grpc: add module utils

v2/nacos/naming/remote/grpc/naming_grpc_client_proxy.py, v2/nacos/naming/remote/grpc/naming_grpc_connection_event_listener.py, v2/nacos/naming/remote/grpc/naming_push_request_handler.py, v2/nacos/naming/remote/http/naming_http_client_proxy.py, v2/nacos/naming/remote/inaming_client_proxy.py, v2/nacos/naming/remote/naming_client_proxy_delegate.py
to solve issue #62
add nacos.naming.remote for module naming
=> [ISSUE #62]Feature support grpc: add nacos.naming.remote for module naming

v2/nacos/naming/core/server_list_manager.py, v2/nacos/naming/core/service_info_update_service.py
to solve issue #59 
add nacos.naming.core for module naming
=> [ISSUE #59]Feature support grpc: add nacos.naming.core for module naming

v2/nacos/naming/nacos_naming_service.py
to solve issue #64 
add nacos.naming.naming.nacos_naming_service for module naming
=> [ISSUE #64]Feature support grpc: add nacos.naming.nacos_naming_service for module naming

v2/nacos/naming/utils/common_params.py, v2/nacos/naming/utils/naming_remote_constants.py, v2/nacos/naming/utils/naming_utils.py, v2/nacos/naming/utils/util_and_coms.py
to solve issue #63 
add nacos.naming.utils for module naming
=> [ISSUE #63]Feature support grpc: add nacos.naming.utils for module naming

v2/nacos/naming/beat/beat_info.py, v2/nacos/naming/beat/beat_reactor.py
to solve issue #57 
add nacos.naming.beat for module naming
=> [ISSUE #57]Feature support grpc: add nacos.naming.beat for module naming

v2/nacos/naming/cache/disk_cache.py, v2/nacos/naming/cache/service_info_holder.py
to solve issue #58 
add nacos.naming.cache for module naming
=> [ISSUE #58]Feature support grpc: add nacos.naming.cache for module naming

v2/nacos/naming/event/instances_change_event.py, v2/nacos/naming/event/instances_change_notifier.py
to solve issue #61
add nacos.naming.event for module naming
=> [ISSUE #61]Feature support grpc: add nacos.naming.event for module naming

v2/nacos/security/security_proxy.py
to solve issue #75
add module security
=> [ISSUE #75]Feature support grpc: add module security

v2/nacos/naming/dtos/abstract_selector.py, v2/nacos/naming/dtos/cluster.py, v2/nacos/naming/dtos/instance.py, v2/nacos/naming/dtos/service.py, v2/nacos/naming/dtos/service_info.py
to solve issue #60 
add nacos.naming.dtos for module naming
=> [ISSUE #60]Feature support grpc: add nacos.naming.dtos for module naming

v2/nacos/security/security_proxy.py
to solve issue #75
modify module security(completed)
=> [ISSUE #75]Feature support grpc: modify module security

v2/nacos/common/constants.py
to solve issue #73
add constants.py for module common
=> [ISSUE #73]Feature support grpc: add constants.py for module common

README.md
update example about namespace value
=> update example about namespace value

nacos/client.py
=> Support naming auth

nacos/client.py
support endpoint url model to get server list and fix add watch fail on mac & linux
=> support endpoint url model to get server list and fix add watch fail on mac & linux 

README.md, nacos/client.py, nacos/task.py
=> 修复传参bug、新增日志轮转、优化明文用户名密码鉴权，支持后台服务实例自动心跳保活

README.md
Fixed a format issue about nested lists.
=> Fixed a format issue.

v2/nacos/transport/nacos_server_connector.py
When get access token failed ,should not inject accessToken into header
=> Fix bug of Inject security info

v2/nacos/naming/model/naming_request.py, v2/nacos/naming/nacos_naming_service.py, v2/nacos/naming/remote/naming_grpc_client_proxy.py
v2 api support persistent instance register and deregister
=> v2 api support persistent instance register and deregister
